### ISSUE TITLE
Navigating between pages doesn't load examples correctly

### ISSUE THREAD

**Issue by jonathanolson** [scenerystack/community#130]
It seems like it's not doing a full page load, and something is going wrong where examples don't show up.

**Comment by jonathanolson** [comment]
Looks like this is part of the "instant" navigation. We COULD turn that off with:

```yaml
theme:
  features:
    - navigation.instant: false
```

However I'll likely be able to adapt sandbox examples to cleanup (with `document$.subscribe`), and we can continue to support the faster AJAX-style loading.
